# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55d1143d914a5b9a2137d823fcccc6dc4936bc9d4e888a07fae44f07f8e6a7371c209784df5098582b3419eb531a03b6bc595706e079506e7c3933787e5482a2

test:
  secret_key_base: a42445ab63abd82d9d54d41807d41ba5b937014ff06d6a6bdd395630c990934d09cdc32612be78f3d8b3e8ce0d390de4b47cc1d76f2c9056ae0e6a2524ac9e25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
